// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StorageHandlerInterface is an autogenerated mock type for the StorageHandlerInterface type
type StorageHandlerInterface struct {
	mock.Mock
}

// ProcessUrl provides a mock function with given fields: url
func (_m *StorageHandlerInterface) ProcessUrl(url string) string {
	ret := _m.Called(url)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
