// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UrlShortnerInterface is an autogenerated mock type for the UrlShortnerInterface type
type UrlShortnerInterface struct {
	mock.Mock
}

// GetShortUrl provides a mock function with given fields: url
func (_m *UrlShortnerInterface) GetShortUrl(url string) (string, error) {
	ret := _m.Called(url)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
